# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
# Pentagonal 	  	Pn=n(3n-1)/2 	  	1, 5, 12, 22, 35, ...
# Hexagonal 	  	Hn=n(2n-1) 	  	1, 6, 15, 28, 45, ...
#
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

import progressbar


def get_pentagonals(bound):

    return [((n * ((3 * n) - 1)) / 2) for n in range(164, bound)]


def get_hexagonals(bound):

    return [(n * ((2 * n) - 1)) for n in range(142, bound)]


def solve(bound):

    print "Generating pentagonals..."
    p_list = get_pentagonals(bound)

    print "Generating hexagonals..."
    h_list = get_hexagonals(bound)

    print "Evaluating..."
    bar = progressbar.ProgressBar(max_value=bound + 1)
    t_list = list(((t * (t + 1)) / 2) for t in range(286, bound))
    counter = 1

    for t in t_list:
        bar.update(counter)
        counter += 1
        if t not in p_list:
            continue
        if t not in h_list:
            continue
        return t

    print " "
    return "Upper bound %d too low." % bound


print solve(100000)
# SOLVED
